name: Build CPython 3.14

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-interpreter:
    name: Interpreter JIT
    runs-on: windows-latest

    steps:
    - name: Checkout CPython
      uses: actions/checkout@v4
      with:
        repository: python/cpython
        ref: main
        path: cpython

    - name: Cache externals
      uses: actions/cache@v4
      with:
        path: cpython/externals
        key: cpython-externals-interpreter-${{ hashFiles('cpython/PCbuild/get_externals.bat') }}

    - name: Build CPython Interpreter JIT
      working-directory: cpython/PCbuild
      run: |
        ./build.bat -e -p x64 --no-tkinter /m:$env:NUMBER_OF_PROCESSORS
      env:
        PYTHON_BUILDDIR: ../build_interpreter
        EnableExperimentalJIT: interpreter

    - name: Upload Interpreter JIT artifact
      uses: actions/upload-artifact@v4
      with:
        name: python314-interpreter-jit-windows-x64
        path: |
          cpython/PCbuild/amd64/*.exe
          cpython/PCbuild/amd64/*.dll
          cpython/PCbuild/amd64/*.pyd
        retention-days: 30